# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('experience_needed', models.CharField(choices=[(0, 'Easyfix'), (1, 'Moderate'), (2, 'Senior')], default=1, max_length=10)),
                ('expected_time', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('tech_stack', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('issue_details', models.TextField()),
                ('issue_number', models.IntegerField()),
                ('issue_url', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('label_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_url', models.CharField(max_length=2000)),
                ('label_name', models.CharField(max_length=100)),
                ('label_color', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_labels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IssueLabel'),
        ),
    ]
