"""
This module contains a sample api data mostly
used for testing of app.
"""

api_response_issues = [
    {
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/12",
        "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
        "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/12/labels{/name}",
        "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/12/comments",
        "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/12/events",
        "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/12",
        "id": 236652934,
        "number": 12,
        "title": "Write test-cases the back end API",
        "user": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "labels": [

        ],
        "state": "open",
        "locked": False,
        "assignee": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "assignees": [
        {
            "login": "razat249",
            "id": 10090911,
            "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/razat249",
            "html_url": "https://github.com/razat249",
            "followers_url": "https://api.github.com/users/razat249/followers",
            "following_url": "https://api.github.com/users/razat249/following{/other_user}",
            "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
            "organizations_url": "https://api.github.com/users/razat249/orgs",
            "repos_url": "https://api.github.com/users/razat249/repos",
            "events_url": "https://api.github.com/users/razat249/events{/privacy}",
            "received_events_url": "https://api.github.com/users/razat249/received_events",
            "type": "User",
            "site_admin": False
        }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2017-06-17T10:29:33Z",
        "updated_at": "2017-06-17T10:30:56Z",
        "closed_at": None,
        "body": "Experience: Moderate\r\nExpected-time: 1 week\r\nLanguage: python\r\nTechnology-stack: Django\r\n\r\n## Description\r\ntest the back end api"
    },
    {
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/11",
        "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
        "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/11/labels{/name}",
        "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/11/comments",
        "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/11/events",
        "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/11",
        "id": 236652841,
        "number": 11,
        "title": "Add Travis-CI for continuous integration",
        "user": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "labels": [

        ],
        "state": "open",
        "locked": False,
        "assignee": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "assignees": [
        {
            "login": "razat249",
            "id": 10090911,
            "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/razat249",
            "html_url": "https://github.com/razat249",
            "followers_url": "https://api.github.com/users/razat249/followers",
            "following_url": "https://api.github.com/users/razat249/following{/other_user}",
            "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
            "organizations_url": "https://api.github.com/users/razat249/orgs",
            "repos_url": "https://api.github.com/users/razat249/repos",
            "events_url": "https://api.github.com/users/razat249/events{/privacy}",
            "received_events_url": "https://api.github.com/users/razat249/received_events",
            "type": "User",
            "site_admin": False
        }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2017-06-17T10:27:01Z",
        "updated_at": "2017-06-17T10:27:01Z",
        "closed_at": None,
        "body": "Experience: Moderate\r\nExpected-time: 1 day\r\nLanguage: yml\r\nTechnology-stack: Django\r\n\r\n## Description\r\nAdd Travis-ci for continuous integration."
    },
    {
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/8",
        "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
        "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/8/labels{/name}",
        "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/8/comments",
        "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/8/events",
        "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/8",
        "id": 235457957,
        "number": 8,
        "title": "Add sorting feature for expected time and experience level",
        "user": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "labels": [

        ],
        "state": "open",
        "locked": False,
        "assignee": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "assignees": [
        {
            "login": "razat249",
            "id": 10090911,
            "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/razat249",
            "html_url": "https://github.com/razat249",
            "followers_url": "https://api.github.com/users/razat249/followers",
            "following_url": "https://api.github.com/users/razat249/following{/other_user}",
            "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
            "organizations_url": "https://api.github.com/users/razat249/orgs",
            "repos_url": "https://api.github.com/users/razat249/repos",
            "events_url": "https://api.github.com/users/razat249/events{/privacy}",
            "received_events_url": "https://api.github.com/users/razat249/received_events",
            "type": "User",
            "site_admin": False
        }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2017-06-13T07:17:21Z",
        "updated_at": "2017-06-13T07:17:21Z",
        "closed_at": None,
        "body": "Experience: Moderate\r\nExpected-time: 1 day\r\nLanguage: Python\r\nTechnology-stack: Django\r\n\r\n## Description\r\nAdd sorting feature for expected time and experience level."
    },
    {
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/7",
        "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
        "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/7/labels{/name}",
        "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/7/comments",
        "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/7/events",
        "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/7",
        "id": 233564738,
        "number": 7,
        "title": "Dockerize Project",
        "user": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "labels": [
        {
            "id": 613678729,
            "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/enhancement",
            "name": "enhancement",
            "color": "84b6eb",
            "default": True
        }
        ],
        "state": "open",
        "locked": False,
        "assignee": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "assignees": [
        {
            "login": "razat249",
            "id": 10090911,
            "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/razat249",
            "html_url": "https://github.com/razat249",
            "followers_url": "https://api.github.com/users/razat249/followers",
            "following_url": "https://api.github.com/users/razat249/following{/other_user}",
            "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
            "organizations_url": "https://api.github.com/users/razat249/orgs",
            "repos_url": "https://api.github.com/users/razat249/repos",
            "events_url": "https://api.github.com/users/razat249/events{/privacy}",
            "received_events_url": "https://api.github.com/users/razat249/received_events",
            "type": "User",
            "site_admin": False
        }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2017-06-05T11:47:01Z",
        "updated_at": "2017-06-06T10:35:57Z",
        "closed_at": None,
        "body": "Experience: Easyfix\r\nExpected-time: 3 hours\r\nLanguage: Python\r\nTechnology-stack Django\r\n\r\n## Description\r\nDockerize this backend project for development and deployment purposes."
    },
    {
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/6",
        "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
        "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/6/labels{/name}",
        "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/6/comments",
        "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/6/events",
        "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/6",
        "id": 233429779,
        "number": 6,
        "title": "Implement expected time feature",
        "user": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "labels": [
        {
            "id": 613678729,
            "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/labels/enhancement",
            "name": "enhancement",
            "color": "84b6eb",
            "default": True
        }
        ],
        "state": "open",
        "locked": False,
        "assignee": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "assignees": [
        {
            "login": "razat249",
            "id": 10090911,
            "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/razat249",
            "html_url": "https://github.com/razat249",
            "followers_url": "https://api.github.com/users/razat249/followers",
            "following_url": "https://api.github.com/users/razat249/following{/other_user}",
            "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
            "organizations_url": "https://api.github.com/users/razat249/orgs",
            "repos_url": "https://api.github.com/users/razat249/repos",
            "events_url": "https://api.github.com/users/razat249/events{/privacy}",
            "received_events_url": "https://api.github.com/users/razat249/received_events",
            "type": "User",
            "site_admin": False
        }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2017-06-04T12:11:53Z",
        "updated_at": "2017-06-06T11:30:33Z",
        "closed_at": None,
        "body": "Experience: Moderate\r\nExpected-time: 1 day\r\nLanguage: Python\r\nTechnology-stack Django\r\n\r\n## Description\r\nRight now the expected time is a string field. It should work logically so that we can easily filter issues with different expected time."
    },
    {
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/4",
        "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
        "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/4/labels{/name}",
        "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/4/comments",
        "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/4/events",
        "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/4",
        "id": 232772370,
        "number": 4,
        "title": "Configure MySQL Database",
        "user": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "labels": [

        ],
        "state": "open",
        "locked": False,
        "assignee": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "assignees": [
        {
            "login": "razat249",
            "id": 10090911,
            "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/razat249",
            "html_url": "https://github.com/razat249",
            "followers_url": "https://api.github.com/users/razat249/followers",
            "following_url": "https://api.github.com/users/razat249/following{/other_user}",
            "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
            "organizations_url": "https://api.github.com/users/razat249/orgs",
            "repos_url": "https://api.github.com/users/razat249/repos",
            "events_url": "https://api.github.com/users/razat249/events{/privacy}",
            "received_events_url": "https://api.github.com/users/razat249/received_events",
            "type": "User",
            "site_admin": False
        }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2017-06-01T05:50:38Z",
        "updated_at": "2017-06-06T11:31:00Z",
        "closed_at": None,
        "body": "Experience: Easyfix\r\nExpected-time: 3 hrs\r\nLanguage: Python, SQL\r\nTechnology-stack Django\r\n\r\n## Description\r\nRight now the app is using a sqllite3 database. Configure it to use MySQL."
    },
    {
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/3",
        "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
        "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/3/labels{/name}",
        "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/3/comments",
        "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/3/events",
        "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/3",
        "id": 232771183,
        "number": 3,
        "title": "Add a fetcher component to periodically fetch issues from GitHub APIs.",
        "user": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "labels": [

        ],
        "state": "open",
        "locked": False,
        "assignee": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "assignees": [
        {
            "login": "razat249",
            "id": 10090911,
            "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/razat249",
            "html_url": "https://github.com/razat249",
            "followers_url": "https://api.github.com/users/razat249/followers",
            "following_url": "https://api.github.com/users/razat249/following{/other_user}",
            "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
            "organizations_url": "https://api.github.com/users/razat249/orgs",
            "repos_url": "https://api.github.com/users/razat249/repos",
            "events_url": "https://api.github.com/users/razat249/events{/privacy}",
            "received_events_url": "https://api.github.com/users/razat249/received_events",
            "type": "User",
            "site_admin": False
        }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2017-06-01T05:40:42Z",
        "updated_at": "2017-06-06T11:31:28Z",
        "closed_at": None,
        "body": "Experience: Senior\r\nExpected-time: 2 days\r\nLanguage: Python\r\nTechnology-stack Django, Celery\r\n\r\n## Description\r\nWe will be using this API for reference: https://api.github.com/repos/razat249/github-view/issues"
    },
    {
        "url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/2",
        "repository_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend",
        "labels_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/2/labels{/name}",
        "comments_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/2/comments",
        "events_url": "https://api.github.com/repos/mozillacampusclubs/issue_parser_backend/issues/2/events",
        "html_url": "https://github.com/mozillacampusclubs/issue_parser_backend/issues/2",
        "id": 232770888,
        "number": 2,
        "title": "Add issue model and API views",
        "user": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "labels": [

        ],
        "state": "open",
        "locked": False,
        "assignee": {
        "login": "razat249",
        "id": 10090911,
        "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/razat249",
        "html_url": "https://github.com/razat249",
        "followers_url": "https://api.github.com/users/razat249/followers",
        "following_url": "https://api.github.com/users/razat249/following{/other_user}",
        "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
        "organizations_url": "https://api.github.com/users/razat249/orgs",
        "repos_url": "https://api.github.com/users/razat249/repos",
        "events_url": "https://api.github.com/users/razat249/events{/privacy}",
        "received_events_url": "https://api.github.com/users/razat249/received_events",
        "type": "User",
        "site_admin": False
        },
        "assignees": [
        {
            "login": "razat249",
            "id": 10090911,
            "avatar_url": "https://avatars1.githubusercontent.com/u/10090911?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/razat249",
            "html_url": "https://github.com/razat249",
            "followers_url": "https://api.github.com/users/razat249/followers",
            "following_url": "https://api.github.com/users/razat249/following{/other_user}",
            "gists_url": "https://api.github.com/users/razat249/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/razat249/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/razat249/subscriptions",
            "organizations_url": "https://api.github.com/users/razat249/orgs",
            "repos_url": "https://api.github.com/users/razat249/repos",
            "events_url": "https://api.github.com/users/razat249/events{/privacy}",
            "received_events_url": "https://api.github.com/users/razat249/received_events",
            "type": "User",
            "site_admin": False
        }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2017-06-01T05:38:06Z",
        "updated_at": "2017-06-06T11:31:56Z",
        "closed_at": None,
        "body": "Experience: Moderate\r\nExpected-time: 2 days\r\nLanguage: Python\r\nTechnology-stack Django\r\n\r\n## Description\r\nAlso, add filter feature."
    }
    ]
