package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/ossn/fixme_backend/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Repository)
// DB Table: Plural (repositories)
// Resource: Plural (Repositories)
// Path: Plural (/repositories)
// View Template Folder: Plural (/templates/repositories/)

// RepositoriesResource is the resource for the Repository model
type RepositoriesResource struct {
	buffalo.Resource
}

// List gets all Repositories. This function is mapped to the path
// GET /repositories
func (v RepositoriesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	repositories := &models.Repositories{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Repositories from the DB
	if err := q.Eager("Project").All(repositories); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, repositories))
}

// Show gets the data for one Repository. This function is mapped to
// the path GET /repositories/{repository_id}
func (v RepositoriesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Repository
	repository := &models.Repository{}

	// To find the Repository the parameter repository_id is used.
	if err := tx.Eager("Project").Find(repository, c.Param("repository_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, repository))
}

// New renders the form for creating a new Repository.
// This function is mapped to the path GET /repositories/new
func (v RepositoriesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Repository{}))
}

// // Create adds a Repository to the DB. This function is mapped to the
// // path POST /repositories
// func (v RepositoriesResource) Create(c buffalo.Context) error {
// 	// Allocate an empty Repository
// 	repository := &models.Repository{}

// 	// Bind repository to the html form elements
// 	if err := c.Bind(repository); err != nil {
// 		return errors.WithStack(err)
// 	}

// 	// Get the DB connection from the context
// 	tx, ok := c.Value("tx").(*pop.Connection)
// 	if !ok {
// 		return errors.WithStack(errors.New("no transaction found"))
// 	}

// 	// Validate the data from the html form
// 	verrs, err := tx.ValidateAndCreate(repository)
// 	if err != nil {
// 		return errors.WithStack(err)
// 	}

// 	if verrs.HasAny() {
// 		// Make the errors available inside the html template
// 		c.Set("errors", verrs)

// 		// Render again the new.html template that the user can
// 		// correct the input.
// 		return c.Render(422, r.Auto(c, repository))
// 	}

// 	// If there are no errors set a success message
// 	c.Flash().Add("success", "Repository was created successfully")

// 	// and redirect to the repositories index page
// 	return c.Render(201, r.Auto(c, repository))
// }

// // Edit renders a edit form for a Repository. This function is
// // mapped to the path GET /repositories/{repository_id}/edit
// func (v RepositoriesResource) Edit(c buffalo.Context) error {
// 	// Get the DB connection from the context
// 	tx, ok := c.Value("tx").(*pop.Connection)
// 	if !ok {
// 		return errors.WithStack(errors.New("no transaction found"))
// 	}

// 	// Allocate an empty Repository
// 	repository := &models.Repository{}

// 	if err := tx.Find(repository, c.Param("repository_id")); err != nil {
// 		return c.Error(404, err)
// 	}

// 	return c.Render(200, r.Auto(c, repository))
// }

// // Update changes a Repository in the DB. This function is mapped to
// // the path PUT /repositories/{repository_id}
// func (v RepositoriesResource) Update(c buffalo.Context) error {
// 	// Get the DB connection from the context
// 	tx, ok := c.Value("tx").(*pop.Connection)
// 	if !ok {
// 		return errors.WithStack(errors.New("no transaction found"))
// 	}

// 	// Allocate an empty Repository
// 	repository := &models.Repository{}

// 	if err := tx.Find(repository, c.Param("repository_id")); err != nil {
// 		return c.Error(404, err)
// 	}

// 	// Bind Repository to the html form elements
// 	if err := c.Bind(repository); err != nil {
// 		return errors.WithStack(err)
// 	}

// 	verrs, err := tx.ValidateAndUpdate(repository)
// 	if err != nil {
// 		return errors.WithStack(err)
// 	}

// 	if verrs.HasAny() {
// 		// Make the errors available inside the html template
// 		c.Set("errors", verrs)

// 		// Render again the edit.html template that the user can
// 		// correct the input.
// 		return c.Render(422, r.Auto(c, repository))
// 	}

// 	// If there are no errors set a success message
// 	c.Flash().Add("success", "Repository was updated successfully")

// 	// and redirect to the repositories index page
// 	return c.Render(200, r.Auto(c, repository))
// }

// // Destroy deletes a Repository from the DB. This function is mapped
// // to the path DELETE /repositories/{repository_id}
// func (v RepositoriesResource) Destroy(c buffalo.Context) error {
// 	// Get the DB connection from the context
// 	tx, ok := c.Value("tx").(*pop.Connection)
// 	if !ok {
// 		return errors.WithStack(errors.New("no transaction found"))
// 	}

// 	// Allocate an empty Repository
// 	repository := &models.Repository{}

// 	// To find the Repository the parameter repository_id is used.
// 	if err := tx.Find(repository, c.Param("repository_id")); err != nil {
// 		return c.Error(404, err)
// 	}

// 	if err := tx.Destroy(repository); err != nil {
// 		return errors.WithStack(err)
// 	}

// 	// If there are no errors set a flash message
// 	c.Flash().Add("success", "Repository was destroyed successfully")

// 	// Redirect to the repositories index page
// 	return c.Render(200, r.Auto(c, repository))
// }
